# Generated by Django 6.0.6 on 2026-06-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('productivity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('consistency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('diversity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leadership', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('collaboration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('innovation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('learning', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'kpi_scores',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='KpiRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kpi_rules',
                'unique_together': {('metric', 'keyword')},
            },
        ),
    ]
