# Generated by Django 6.0.6 on 2026-06-06 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('worklogs', '0002_add_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tasks.task'),
        ),
    ]
